Project_CE030_CE014/MMT/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MMT;
using MMT.Models;

namespace MMT.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BookingsController : Controller
    {
        private readonly PackageDbContext _context;

        public BookingsController(PackageDbContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Bookings.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .FirstOrDefaultAsync(m => m.BookingID == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingID,PackageName,NumberofPersons,JourneyDate,email,city,PaymentMethod,Amount,status")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingID,PackageName,NumberofPersons,JourneyDate,email,city,PaymentMethod,Amount,status")] Booking booking)
        {
            if (id != booking.BookingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .FirstOrDefaultAsync(m => m.BookingID == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings.FindAsync(id);
            _context.Bookings.Remove(booking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.BookingID == id);
        }
    }
}

Project_CE030_CE014/MMT/Controllers/DcardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MMT;
using MMT.Models;

namespace MMT.Controllers
{
    public class DcardsController : Controller
    {
        private readonly PackageDbContext _context;

        public DcardsController(PackageDbContext context)
        {
            _context = context;
        }

        // GET: Dcards
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cards.ToListAsync());
        }

        // GET: Dcards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dcard = await _context.Cards
                .FirstOrDefaultAsync(m => m.ID == id);
            if (dcard == null)
            {
                return NotFound();
            }

            return View(dcard);
        }

        // GET: Dcards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dcards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CardNumber,month,year,CVV,mailid,balance")] Dcard dcard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dcard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dcard);
        }

        // GET: Dcards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dcard = await _context.Cards.FindAsync(id);
            if (dcard == null)
            {
                return NotFound();
            }
            return View(dcard);
        }

        // POST: Dcards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CardNumber,month,year,CVV,mailid,balance")] Dcard dcard)
        {
            if (id != dcard.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dcard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DcardExists(dcard.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dcard);
        }

        // GET: Dcards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dcard = await _context.Cards
                .FirstOrDefaultAsync(m => m.ID == id);
            if (dcard == null)
            {
                return NotFound();
            }

            return View(dcard);
        }

        // POST: Dcards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dcard = await _context.Cards.FindAsync(id);
            _context.Cards.Remove(dcard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DcardExists(int id)
        {
            return _context.Cards.Any(e => e.ID == id);
        }
    }
}

Project_CE030_CE014/MMT/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MMT.Models;
using MailKit.Net.Smtp;
using MimeKit;
using MimeKit.Text;
using MailKit.Security;

namespace MMT.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly PackageDbContext _context;
        
        public string SessionAmt1 = "_Amt1";
        public string SessionOtp1 = "_OTP1";
        public string Sessioncard1 = "_card1";
        public string Sessionpkgid1 = "_pkgid1";

        public PaymentController(PackageDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Dopayment(string username, int persons, string startdate, string email, string city, string payments)
        {
            ViewBag.amt = TempData["amount1"];
            int total = persons * (int)TempData["amount1"];
            HttpContext.Session.SetInt32(SessionAmt1, total);
            string total1 = total.ToString(); 
            
           var transaction = new  Booking { PackageName= (string)TempData["packagename"],NumberofPersons=persons,JourneyDate=startdate,email=email,city=city,PaymentMethod=payments,Amount=total1,status="Failed"};
           _context.Add(transaction);
            await _context.SaveChangesAsync();

            ViewBag.total = total;
           
            /*ViewBag.name = username;
            ViewBag.method = payments;
            ViewBag.person = persons;*/
            if (payments=="card")
            {
                return View("Dopayment");
            }

            return View("Netbanking");
        }

        public async Task<IActionResult> Cardpayment(string cardno,int mm,int yy,int cvv)
        {
            var card = await _context.Cards
               .FirstOrDefaultAsync(m => m.CardNumber ==cardno);
            HttpContext.Session.SetString(Sessioncard1, cardno);
            var booking = _context.Bookings
                .OrderByDescending(a => a.BookingID)
                .First();
            var mailid = card.mailid;
            ViewBag.mail = mailid;
            ViewBag.paymentStatus = "fail";
            ViewBag.pkgid = (int)TempData["packageid"];
            HttpContext.Session.SetInt32(Sessionpkgid1, (int)TempData["packageid"]);
            if (card==null)
            {
                ViewBag.message1 = "Payment failed due to wrong card number!";
            }
            else
            {
                
                if(card.month!=mm || (card.year!=yy || card.CVV!=cvv))
                {
                    ViewBag.message1 = "Payment failed due to wrong card Details!";
                }
                else if(card.balance< HttpContext.Session.GetInt32(SessionAmt1))
                {
                    ViewBag.message1 = "Payment failed due to insufficient balance!";
                }
                else
                {
                    var random = new Random();
                    int OTP = random.Next(100001, 999999);
                    HttpContext.Session.SetInt32(SessionOtp1, OTP);
                    var email = new MimeMessage();
                    email.From.Add(MailboxAddress.Parse("Verify@MMT.com"));
                    email.To.Add(MailboxAddress.Parse(mailid));
                    email.Subject = "OTP for your Debit Card Payment";
                    email.Body = new TextPart(TextFormat.Plain) { Text = "Your OTP Via Debit card Payment on MMT is "+OTP };

                    using var smtp = new SmtpClient();
                    smtp.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
                    smtp.Authenticate("freerechargepaymentsltd@gmail.com", "urvishdevani@");
                    smtp.Send(email);
                    smtp.Disconnect(true);
                    return View("OTP");

                    /*card.balance = (int)(card.balance - HttpContext.Session.GetInt32(SessionAmt1));
                    booking.status = "Booked";
                    _context.Update(booking);
                    _context.Update(card);

                    await _context.SaveChangesAsync();
                    ViewBag.paymentStatus = "success";
                    ViewBag.message1 = "woohoo! Your payment is successfull. Enjoy your Trip :)";*/
                }
            }
            return View();
        }

        public async Task<IActionResult> OTPPayment(string otp1)
        {
            if(otp1 == (HttpContext.Session.GetInt32(SessionOtp1)).ToString())
            {
                var card = await _context.Cards
             .FirstOrDefaultAsync(m => m.CardNumber == HttpContext.Session.GetString(Sessioncard1));
                var booking = _context.Bookings
                   .OrderByDescending(a => a.BookingID)
                   .First();
                card.balance = (int)(card.balance - HttpContext.Session.GetInt32(SessionAmt1));
                booking.status = "Booked";
                _context.Update(booking);
                _context.Update(card);
                ViewBag.tid = booking.BookingID;

                await _context.SaveChangesAsync();
                ViewBag.paymentStatus = "success";
                ViewBag.message1 = "woohoo! Your payment is successfull. Enjoy your Trip :)";
                return View("Cardpayment");
            }
            else
            {
                ViewBag.pkgid = HttpContext.Session.GetInt32(Sessionpkgid1);
                ViewBag.paymentStatus = "fail";
                ViewBag.message1 = "Payment failed due to Wrong OTP! Please Try again";
                return View("Cardpayment");
            }
           

        }


        public async Task<IActionResult> Netbankingpayment(string bank, string uname,string passwd)
        {
            var bankuser = await _context.Netbankings
              .FirstOrDefaultAsync(m => m.Username == uname);
            ViewBag.paymentStatus = "fail";
            var booking = _context.Bookings
                .OrderByDescending(a => a.BookingID)
                .First();
            ViewBag.pkgid = (int)TempData["packageid"];
            if (bankuser == null)
            {
                ViewBag.message1 = "Payment failed because Invalid Username!";
            }
            else
            {
                if (bankuser.Password != passwd || bankuser.Bank!=bank)
                {
                    ViewBag.message1 = "Payment failed due to Invalid password or Bank!";
                }
                else if (bankuser.balance < HttpContext.Session.GetInt32(SessionAmt1))
                {
                    ViewBag.message1 = "Payment failed due to insufficient balance!";
                }
                else
                {
                    bankuser.balance = (int)(bankuser.balance - HttpContext.Session.GetInt32(SessionAmt1));
                    booking.status = "Booked";
                    ViewBag.tid = booking.BookingID;
                    _context.Update(booking);
                    _context.Update(bankuser);
                    await _context.SaveChangesAsync();
                    ViewBag.paymentStatus = "success";
                    ViewBag.message1 = "woohoo! Your payment is successfull. Enjoy your Trip :)";
                }
            }


            return View("Cardpayment");
        }
        [AllowAnonymous]
        public  IActionResult ContactUs()
        {

            return View("ContactUs");
        }
    }
}

Project_CE030_CE014/MMT/Views/Shared/Cancel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <h1 style="color:red">Your Booking has been Cancelled</h1>
    <br />
    <h1>₹@ViewBag.amt will be refunded your original Payment method within 7 Working Days</h1>
    <div>
        <a class="button button2" asp-action="Index" asp-controller="Home" style="margin-right: 20px">Homepage</a>
    </div>
}

Project_CE030_CE014/MMT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>@ViewData["Title"] - MMT</title>
    <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     <link rel="stylesheet" href="~/css/site.css" />-->

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="footer, address, phone, icons" />
    <title>Untitled</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/assets/css/gradient-navbar-1.css">
    <link rel="stylesheet" href="~/assets/css/gradient-navbar.css">
    <link href="~/css/allpackages.css" rel="stylesheet" />
    <link href="~/css/Dcard.css" rel="stylesheet" />
    <link href="~/css/netbanking.css" rel="stylesheet" />

    <!-- <script src="~/assets/js/homepage.js"></script>-->
    <link href="~/assets/css/indexpage.css" rel="stylesheet" />


    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/css/homepage.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>


    <!--<style src="~/css/homepage.css"/>-->
</head>
<body>
    <header>
        <nav class="navbar navbar-dark navbar-expand-md" id="app-navbar" style="margin-top:-40px">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><i class="icon ion-ios-infinite" id="brand-logo"></i></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link active" asp-controller="home" asp-action="Index">Home</a></li>
                        @if (User.IsInRole("Admin"))
                        {

                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="packages" asp-action="Index">Manage Packages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Bookings" asp-action="Index">All Bookings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Dcards" asp-action="Index">Debit Cards</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Netbankings" asp-action="Index">Netbanking</a>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item"><a class="nav-link" asp-controller="AllPackage" asp-action="Index">Packages</a></li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="CustomerBooking" asp-action="Index">My Bookings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Payment" asp-action="ContactUs">Contact Us</a>
                            </li>

                        }

                        <partial name="_LoginPartial.cshtml" />
                    </ul>
                </div>
            </div>
        </nav>
        <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MMT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>

            </div>

        </nav>-->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MMT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <footer class="footer-distributed" style="position:relative">

        <div class="footer-left">

            <h3>About <span>Make My Trip</span></h3>

            <p class="footer-links">
                <a asp-controller="home" asp-action="Index">Home</a>
                |
                <a asp-controller="Payment" asp-action="ContactUs">Contact</a>
            </p>

            <p class="footer-company-name">© 2020 MMT Pvt. Ltd.</p>
        </div>

        <div class="footer-center">
            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>Surat-395006</span></p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+918780484915</p>
            </div>
            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:devaniurvish881@gmail.com">support@mmt.com</a></p>
            </div>
        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span>About the site</span>

            </p>
            <div class="footer-icons">
                <a href="http://www.facebook.com"><i class="fa fa-facebook"></i></a>
                <a href="http://www.twitter.com"><i class="fa fa-twitter"></i></a>
                <a href="http://www.instagram.com"><i class="fa fa-instagram"></i></a>
                <a href="http://www.linkedin.com"><i class="fa fa-linkedin"></i></a>
                <a href="http://www.youtube.com"><i class="fa fa-youtube"></i></a>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>